import type { FlowEdge, FlowNode } from './store'
import type { ClickTarget, Workflow, WorkflowNode } from './types'

/** Convert the live React Flow graph into the serializable workflow shape. */
export function toWorkflow(nodes: FlowNode[], edges: FlowEdge[], name: string): Workflow {
  return {
    name,
    version: 1,
    nodes: nodes.map((n) => ({
      id: n.id,
      kind: n.data.kind,
      title: n.data.title,
      x: Math.round(n.position.x),
      y: Math.round(n.position.y),
      config: { ...n.data.config },
    })),
    edges: edges.map((e) => ({ source: e.source, target: e.target })),
  }
}

/** Linear execution order: walk the single outgoing edge from Start. */
export function orderedSteps(wf: Workflow): WorkflowNode[] {
  const byId = new Map(wf.nodes.map((n) => [n.id, n]))
  const next = new Map<string, string>()
  for (const e of wf.edges) {
    if (!next.has(e.source)) next.set(e.source, e.target)
  }
  const start = wf.nodes.find((n) => n.kind === 'start')
  if (!start) return []
  const ordered: WorkflowNode[] = []
  const seen = new Set<string>()
  let current: WorkflowNode | undefined = start
  while (current && !seen.has(current.id)) {
    seen.add(current.id)
    ordered.push(current)
    if (current.kind === 'stop') break
    const targetId = next.get(current.id)
    current = targetId ? byId.get(targetId) : undefined
  }
  return ordered
}

function asNumber(value: unknown, fallback: number): number {
  const n = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(n) ? n : fallback
}

/** Validation mirrors the runtime so the editor and the exported script agree. */
export function validate(wf: Workflow): string[] {
  const errors: string[] = []
  const starts = wf.nodes.filter((n) => n.kind === 'start')
  const stops = wf.nodes.filter((n) => n.kind === 'stop')
  if (starts.length !== 1) errors.push('需要且只能有一个 Start 节点。')
  if (stops.length < 1) errors.push('需要至少一个 Stop 节点。')

  for (const node of wf.nodes) {
    const prefix = node.title || node.kind
    if (node.kind === 'find_image') {
      const hasImage = String(node.config.templateData ?? '').length > 0
      const hasPath = String(node.config.template ?? '').trim().length > 0
      if (!hasImage && !hasPath) {
        errors.push(`${prefix}：请选择模板图片或填写图片路径。`)
      }
      const t = asNumber(node.config.threshold, 0.85)
      if (t < 0 || t > 1) errors.push(`${prefix}：置信度需在 0 和 1 之间。`)
    }
    if (node.kind === 'click') {
      const target = (node.config.target as ClickTarget) ?? 'fixed'
      if (target !== 'fixed' && target !== 'last_match') {
        errors.push(`${prefix}：未知的点击目标。`)
      }
    }
    if (node.kind === 'delay') {
      const lo = asNumber(node.config.min_seconds, 0.5)
      const hi = asNumber(node.config.max_seconds, lo)
      if (lo < 0 || hi < 0) errors.push(`${prefix}：延迟不能为负。`)
    }
  }

  const ordered = orderedSteps(wf)
  if (starts.length === 1 && !ordered.some((n) => n.kind === 'stop')) {
    errors.push('从 Start 出发无法到达任何 Stop 节点，请把节点连起来。')
  }
  return errors
}

/** Produce a Python string literal (double-quoted) from any text. */
function pyStr(value: unknown): string {
  return JSON.stringify(String(value ?? ''))
}

/** Extract the raw base64 payload from a `data:image/...;base64,XXXX` URL. */
function templateBase64(value: unknown): string {
  const s = String(value ?? '')
  const comma = s.indexOf(',')
  return s.startsWith('data:') && comma >= 0 ? s.slice(comma + 1) : ''
}

const PY_HEADER = `#!/usr/bin/env python3
"""Generated by FlowPilot Studio — do not edit by hand.

Run locally:  pip install opencv-python mss numpy pyautogui
              python this_script.py

Safety: PyAutoGUI fail-safe is ON — slam the mouse into a screen corner to abort.
"""
from __future__ import annotations

import base64
import random
import sys
import time

import cv2
import mss
import numpy as np
import pyautogui

pyautogui.FAILSAFE = True


def grab_screen() -> np.ndarray:
    with mss.mss() as sct:
        frame = np.asarray(sct.grab(sct.monitors[0]))
    return cv2.cvtColor(frame, cv2.COLOR_BGRA2BGR)


def template_from_base64(data: str) -> np.ndarray:
    raw = np.frombuffer(base64.b64decode(data), np.uint8)
    image = cv2.imdecode(raw, cv2.IMREAD_COLOR)
    if image is None:
        raise ValueError("embedded template image could not be decoded")
    return image


def match_template(template, threshold: float):
    if template is None:
        raise FileNotFoundError("template image could not be loaded")
    screen = grab_screen()
    scores = cv2.matchTemplate(screen, template, cv2.TM_CCOEFF_NORMED)
    _, confidence, _, location = cv2.minMaxLoc(scores)
    if confidence < threshold:
        return None
    h, w = template.shape[:2]
    return (location[0] + w // 2, location[1] + h // 2, float(confidence))
`

export function exportPython(wf: Workflow): string {
  const ordered = orderedSteps(wf)
  const body: string[] = []
  const ind = '    '

  body.push(`${ind}print("FlowPilot — ${escapeComment(wf.name)} (starting in 3s, move mouse to a corner to abort)")`)
  body.push(`${ind}time.sleep(3)`)
  body.push(`${ind}last_match = None`)

  for (const node of ordered) {
    const title = escapeComment(node.title)
    body.push('')
    body.push(`${ind}# ${node.kind}: ${title}`)
    body.push(`${ind}print(${pyStr(`[${node.kind}] ${node.title}`)})`)

    switch (node.kind) {
      case 'find_image': {
        const threshold = asNumber(node.config.threshold, 0.85)
        const b64 = templateBase64(node.config.templateData)
        if (b64) {
          body.push(`${ind}template = template_from_base64(`)
          body.push(`${ind}${ind}"${b64}"`)
          body.push(`${ind})`)
          body.push(`${ind}last_match = match_template(template, ${threshold})`)
        } else {
          body.push(
            `${ind}last_match = match_template(cv2.imread(${pyStr(node.config.template)}, cv2.IMREAD_COLOR), ${threshold})`,
          )
        }
        body.push(`${ind}if last_match is None:`)
        body.push(`${ind}${ind}print("image not found, stopping.", file=sys.stderr)`)
        body.push(`${ind}${ind}return 1`)
        body.push(`${ind}print(f"  matched at {last_match[0]},{last_match[1]} ({last_match[2]:.1%})")`)
        break
      }
      case 'click': {
        const target = (node.config.target as ClickTarget) ?? 'fixed'
        if (target === 'last_match') {
          body.push(`${ind}if last_match is None:`)
          body.push(`${ind}${ind}print("no prior image match to click, stopping.", file=sys.stderr)`)
          body.push(`${ind}${ind}return 1`)
          body.push(`${ind}pyautogui.click(last_match[0], last_match[1])`)
        } else {
          const x = Math.round(asNumber(node.config.x, 0))
          const y = Math.round(asNumber(node.config.y, 0))
          body.push(`${ind}pyautogui.click(${x}, ${y})`)
        }
        break
      }
      case 'type_text': {
        body.push(`${ind}pyautogui.write(${pyStr(node.config.text)}, interval=0.02)`)
        break
      }
      case 'delay': {
        const lo = asNumber(node.config.min_seconds, 0.5)
        const hi = asNumber(node.config.max_seconds, lo)
        const a = Math.min(lo, hi)
        const b = Math.max(lo, hi)
        body.push(`${ind}time.sleep(random.uniform(${a}, ${b}))`)
        break
      }
      case 'start':
      case 'stop':
        break
    }
  }

  body.push('')
  body.push(`${ind}print("Workflow completed.")`)
  body.push(`${ind}return 0`)

  return [
    PY_HEADER,
    '',
    'def main() -> int:',
    body.join('\n'),
    '',
    '',
    'if __name__ == "__main__":',
    '    raise SystemExit(main())',
    '',
  ].join('\n')
}

function escapeComment(text: string): string {
  return text.replace(/[\r\n]+/g, ' ')
}

export function exportJson(wf: Workflow): string {
  return JSON.stringify(wf, null, 2)
}
